### PR TITLE
Allow partitioning by ANTENNA1

### PR DESCRIPTION
**Pull request by tnakazato**
Antenna partition only processes autocorrelation, i.e., all cross-correlation data will be discarded. So it is useful only for single-dish data processing.

This is related to Issue #9. **Please note that this is a draft PR just to show you an idea on what is actually requested in #9 (please see below for missing development items).** Point is to allow separating data per antenna both **on memory and disk**. 

This PR allows to set "ANTENNA1" to `partition_scheme`. If "ANTENNA1" is specified, processing set is separated by antenna and each processing set includes only auto-correlation data. 

```python
convert_msv2_to_processing_set(
    in_file=in_file,
    out_file=out_file,
    partition_scheme=['FIELD_ID', 'ANTENNA1'],
    parallel=False,
    overwrite=True,
)
```

The above command will produce more granular processing sets separated by antenna and ANTENNA_ID will be shown in the log message like below.

```
[2024-08-09 15:09:41,986]     INFO      client:  Partition scheme that will be used: ['DATA_DESC_ID', 'OBS_MODE', 'OBSERVATION_ID', 'FIELD_ID', 'ANTENNA1'] 
[2024-08-09 15:09:43,453]     INFO      client:  Number of partitions: 156 
[2024-08-09 15:09:43,453]     INFO      client:  OBSERVATION_ID [0], DDI [0], STATE [10], FIELD [1], SCAN [ 2  4  6  8 10 12], ANTENNA [0] 
[2024-08-09 15:09:43,895]     INFO      client:  OBSERVATION_ID [0], DDI [0], STATE [10], FIELD [1], SCAN [ 2  4  6  8 10 12], ANTENNA [1] 
[2024-08-09 15:09:44,318]     INFO      client:  OBSERVATION_ID [0], DDI [0], STATE [10], FIELD [1], SCAN [ 2  4  6  8 10 12], ANTENNA [2] 
[2024-08-09 15:09:44,744]     INFO      client:  OBSERVATION_ID [0], DDI [0], STATE [11], FIELD [1], SCAN [ 2  4  6  8 10 12], ANTENNA [0] 
[2024-08-09 15:09:45,188]     INFO      client:  OBSERVATION_ID [0], DDI [0], STATE [11], FIELD [1], SCAN [ 2  4  6  8 10 12], ANTENNA [1] 
[2024-08-09 15:09:45,611]     INFO      client:  OBSERVATION_ID [0], DDI [0], STATE [11], FIELD [1], SCAN [ 2  4  6  8 10 12], ANTENNA [2]
```

Development is incomplete. At least, `convert_msv2_to_processing_set` should be updated so that,

* it creates antenna_xds that only contains selected antenna, and 
* it also creates pointing_xds that only contains pointing data for selected antenna.

### CODE REVIEW

**Review by FedeMPouzols — APPROVED** [review]
Hi @tnakazato , @Jan-Willem  had asked me to take a look at this PR to see if we can merge it. Sorry for the delay!                                                                                                                                             
I think this is very close to ready, if not ready. Here is what I did and could see:
                                                              
- I took the branch from your fork into this repo, here: https://github.com/casangi/xradio/tree/sd-partition-antenna, so that I can commit to the branch and it runs the normal CI actions
- the branch has been updated to recent main (note that there have been many recent changes and files have been renamed or moved around), 
- then added a couple of commits with what I think would be needed to make this work. 

Please feel free to take these commits to your fork as needed, or to use the branch that I worked on.

In the `correlated` stakeholder tests, I've added the new partition scheme to the SD datasets. Note that for some datasets this might be risky, as the number of partitions grows significantly.

What I've added to the branch should address the issue of selecting only one antenna (the problem I found was in the replacement of antenna_ids with antenna_name).
This modification fits quite well in the current conversion code. Once the `antenna_xds` is selected down to the only antenna present in the partition, this selection propagates to the `pointing_xds` via the `ant_xds_name_ids` parameter. The selection also propagates the same way to the `system_calibration_xds`.
                                                                                                                                          
I have not done very extensive testing but what is in this PR looks good to me and I think that with the changes proposed in the commits that I added it is working well.

**Review by Jan-Willem — APPROVED** [review]

**Comment by tnakazato** [comment]
Thanks @FedeMPouzols. I incorporated your change into my branch. I confirmed that both antenna_xds and pointing_xds contains single antenna. Remaining issues listed in the original comment were all solved.

I also merged latest main. There was a conflict while merging main. @FedeMPouzols, @Jan-Willem, please check if my manual tweak doesn't break the code.  If the code is in good shape, I think this PR is ready for merge.

**Comment by FedeMPouzols** [comment]
@tnakazato : this looks good to me. That conflict resolution makes sense as there were modifications in approximately the same lines coming from two different branches.

To explain what is going on in the conflict lines. In this if block we could have, if we wanted shorter code:
```
--- a/src/xradio/measurement_set/_utils/_msv2/conversion.py
+++ b/src/xradio/measurement_set/_utils/_msv2/conversion.py
@@ -1177,14 +1177,11 @@ def antenna_ids_to_names(
             }
         )
     else:
-        if not with_antenna_partitioning:
-            # baseline_antenna1_id will be removed soon below, but it is useful here to know the actual antenna_ids,
-            # as opposed to the baseline_ids which can mismatch when data is missing for some antennas
-            xds["baseline_id"] = ant_xds["antenna_name"].sel(
-                antenna_id=xds["baseline_antenna1_id"]
-            )
-        else:
-            xds["baseline_id"] = ant_xds["antenna_name"]
+        # baseline_antenna1_id will be removed soon below, but it is useful here to know the actual antenna_ids,
+        # as opposed to the baseline_ids which can mismatch when data is missing for some antennas
+        xds["baseline_id"] = ant_xds["antenna_name"].sel(
+            antenna_id=xds["baseline_antenna1_id"]
+        )
 
         unwanted_coords_from_ant_xds = [
             "antenna_id",
```
as the general case ("not with_antenna_partitioning") now also works for the one-antenna case (that wasn't the case some weeks ago before some fixes required to make this function work when the main table doesn't have data for some antennas - #271). But as it is I think it is clear what is meant.

**Comment by tnakazato** [comment]
closes #9

**Pull request merged**
